apiVersion: apps/v1
kind: Deployment
metadata:
  name: "todo-app"
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Release.Name}}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-vol
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - configMap:
          name: nginx_conf
          items:
            - key: nginx.conf
              path: nginx.conf
          name: nginx-conf-vol