apiVersion: v1
kind: Service
metadata:
  name: ben-todo-frontend
spec:
  selector:
    app: todo-frontend
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.appPort }}
