apiVersion: v1
kind: Service
metadata:
  name: ben-todo-backend
spec:
  selector:
    app: {{ .Release.Name}}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
