apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}-backend
spec:
  selector:
    app: {{ .Values.nameOverride }}-backend
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.appPort }}
